### ISSUE TITLE
[bug] ECONNRESET not recovered by autoReconnect

### ISSUE THREAD

**Issue by Eccleria** [PLhery/node-twitter-api-v2#374] opened 2022-09-21 18:02 UTC
I'm using this library for the `.stream` part. I've read the discussion #92 about connection errors and I understood that the `stream.autoReconnectRetries = Infinity;` should mitigate some part of the error by automatically try to reconnect the stream.
But apparently it is not the case. A few days ago, my console prompt me the following errors, without `Twitter Event:Reconnected` console prompt:

```javascript
Twitter Event:Error: {"type":"connection error","error":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"message":"Connection lost or closed by Twitter."}
Twitter Event:ReconnectAttempt 0
Twitter Event:ReconnectError 0
Twitter Event:Error: {"type":"reconnect error","error":{"type":"response","code":429,"error":{"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}},"message":"Reconnect error - 1 attempts made yet."}
Twitter Event:ReconnectAttempt 1
Twitter Event:ReconnectError 1
Twitter Event:Error: {"type":"reconnect error","error":{"type":"response","code":429,"error":{"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}},"message":"Reconnect error - 2 attempts made yet."}
Twitter Event:ReconnectAttempt 2
```

As event listeners, I have this:

```javascript
const onConnection = (client) => {
  //some discordjs stuff
  console.log("Twitter Event:Connected");
};

const onConnectionClosed = async (client) => {
  //some discordjs stuff
  console.log("Twitter Event:ConnectionClosed");
};

export const twitterListeners = (stream, client) => {
  stream.on(ETwitterStreamEvent.Connected, async () => {
    onConnection(client)
  });
  stream.on(ETwitterStreamEvent.ConnectionLost, async () => {
    console.log("Twitter Event:ConnectionLost");
  });
  stream.on(ETwitterStreamEvent.ConnectionError, async (data) => {
    console.log("Twitter Event:ConnectionError", data);
  });
  stream.on(ETwitterStreamEvent.ConnectionClosed, async () => {
    onConnectionClosed(client);
  });

  stream.on(ETwitterStreamEvent.Error, async (error) => {
    console.log(`Twitter Event:Error: ${JSON.stringify(error)}`);
  });

  stream.on(ETwitterStreamEvent.ReconnectAttempt, async (data) => {
    console.log("Twitter Event:ReconnectAttempt", data);
  });
  stream.on(ETwitterStreamEvent.Reconnected, async () => {
    console.log("Twitter Event:Reconnected");
  });
  stream.on(ETwitterStreamEvent.ReconnectError, async (data) => {
    console.log("Twitter Event:ReconnectError", data);
  });
  stream.on(ETwitterStreamEvent.ReconnectLimitExceeded, async () => {
    console.log("Twitter Event:ReconnectLimitExceeded");
  });
}
```

I tried to use my twitter `connect/disconnect` commands but it didn't work:

```javascript
//disconnect
stream.autoReconnect = false;
stream.destroy();
const newStream = twitter.searchStream({ expansions: "author_id", autoConnect: false });

//connect
const args = { autoReconnect: true, autoReconnectRetries: Infinity };
newStream.connect(args); //connect stream
```

I don't exactly know how to handle this issue, thanks for your help. If some information is missing please tell me.

I am using
 - Node.js v16.14.2
 - Lib version ^1.12.5
 - Windows 10

**Comment by alkihis** [comment] 2022-09-23 06:47
We don't know how to handle the issue either.
All connections are closed on our side (we ask Node.js to close the socket), and we wait. This is all we can do to mitigate the issue.
This is in fact a duplicate of #92, so I will close this as won't fix. (unless you find an alternative fix)

**Closed by alkihis** 2022-09-23 06:47 UTC
